#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import { pathToFileURL } from "node:url";

const WORKSPACE_DIR = ".agent-workspaces";
const OVERLAY_DIR = "overlay";
const SKILLS_DIR = ".agents/skills";
const SOURCES_DIR = "sources";
const EXTEND_FILE = "AGENTS.extend.md";
const MANIFEST_FILE = "manifest.json";
const IGNORE_FILE = ".awsoignore";
const OVERRIDE_FILE = "AGENTS.override.md";
const BLOCK_START = "# >>> awso";
const BLOCK_END = "# <<< awso";
const GENERATED_MARKER = "GENERATED BY awso.";

class OverlayError extends Error {
  constructor(message, exitCode = 3) {
    super(message);
    this.exitCode = exitCode;
  }
}

function runGit(cwd, args, { allowFailure = false } = {}) {
  const result = spawnSync("git", ["-C", cwd, ...args], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (result.error) throw new OverlayError(`Unable to run Git: ${result.error.message}`);
  if (!allowFailure && result.status !== 0) {
    const detail = (result.stderr || result.stdout).trim();
    throw new OverlayError(detail || `git ${args.join(" ")} failed`);
  }
  return { status: result.status ?? 1, stdout: result.stdout, stderr: result.stderr };
}

function discoverRepository(cwd = process.cwd()) {
  const rootResult = runGit(cwd, ["rev-parse", "--show-toplevel"], { allowFailure: true });
  if (rootResult.status !== 0) throw new OverlayError("Current directory is not inside a Git worktree.");

  const currentRoot = path.resolve(rootResult.stdout.trim());
  const commonDir = path.resolve(
    currentRoot,
    runGit(currentRoot, ["rev-parse", "--path-format=absolute", "--git-common-dir"]).stdout.trim(),
  );
  const worktrees = runGit(currentRoot, ["-c", "core.quotePath=false", "worktree", "list", "--porcelain"])
    .stdout.split(/\r?\n/)
    .filter((line) => line.startsWith("worktree "))
    .map((line) => line.slice("worktree ".length));
  if (worktrees.length === 0) throw new OverlayError("Git did not report a main worktree.");

  return {
    currentRoot,
    mainRoot: path.resolve(worktrees[0]),
    commonDir,
    workspaceRoot: path.join(path.resolve(worktrees[0]), WORKSPACE_DIR),
  };
}

function workspacePaths(repo) {
  return {
    root: repo.workspaceRoot,
    overlay: path.join(repo.workspaceRoot, OVERLAY_DIR),
    sources: path.join(repo.workspaceRoot, SOURCES_DIR),
    extend: path.join(repo.workspaceRoot, SOURCES_DIR, EXTEND_FILE),
    manifest: path.join(repo.workspaceRoot, MANIFEST_FILE),
    exclude: path.join(repo.commonDir, "info", "exclude"),
    override: path.join(repo.currentRoot, OVERRIDE_FILE),
  };
}

function exists(target) {
  try {
    fs.lstatSync(target);
    return true;
  } catch (error) {
    if (error.code === "ENOENT") return false;
    throw error;
  }
}

function atomicWrite(file, content) {
  const parent = path.dirname(file);
  fs.mkdirSync(parent, { recursive: true });
  const temporary = path.join(parent, `.${path.basename(file)}.${process.pid}.${randomUUID()}.tmp`);
  const mode = exists(file) ? fs.statSync(file).mode & 0o777 : 0o644;
  try {
    fs.writeFileSync(temporary, content, { encoding: "utf8", mode });
    fs.renameSync(temporary, file);
  } finally {
    try { fs.unlinkSync(temporary); } catch (error) { if (error.code !== "ENOENT") throw error; }
  }
}

function validateRelativePath(value) {
  if (typeof value !== "string" || value.length === 0) throw new OverlayError("Manifest paths must be non-empty strings.");
  if (/[\0\r\n]/.test(value)) throw new OverlayError("Overlay paths may not contain control-line characters.");
  if (value.includes("\\")) throw new OverlayError(`Overlay path must use '/' separators: ${value}`);
  if (value.startsWith("/") || path.posix.isAbsolute(value)) throw new OverlayError(`Overlay path must be repository-relative: ${value}`);
  const parts = value.split("/");
  if (parts.some((part) => part === "" || part === "." || part === "..")) throw new OverlayError(`Invalid overlay path: ${value}`);
  if (parts[0] === WORKSPACE_DIR || parts[0] === ".git" || parts[0] === OVERRIDE_FILE) {
    throw new OverlayError(`Reserved overlay path: ${value}`);
  }
  if (path.posix.normalize(value) !== value) throw new OverlayError(`Overlay path is not normalized: ${value}`);
  return value;
}

function validateManifest(value) {
  if (!value || value.version !== 1 || !Array.isArray(value.files)) {
    throw new OverlayError("manifest.json must contain version 1 and a files array.");
  }
  const files = value.files.map(validateRelativePath);
  if (new Set(files).size !== files.length) throw new OverlayError("manifest.json contains duplicate paths.");
  if (JSON.stringify(files) !== JSON.stringify([...files].sort())) throw new OverlayError("manifest.json paths must be sorted.");
  return { version: 1, files };
}

function readManifest(file) {
  if (!exists(file)) throw new OverlayError(`Workspace manifest is missing: ${file}`);
  if (!fs.lstatSync(file).isFile()) throw new OverlayError(`Workspace manifest must be a regular file: ${file}`);
  try {
    return validateManifest(JSON.parse(fs.readFileSync(file, "utf8")));
  } catch (error) {
    if (error instanceof OverlayError) throw error;
    throw new OverlayError(`Invalid workspace manifest: ${error.message}`);
  }
}

function manifestText(files) {
  return `${JSON.stringify({ version: 1, files: [...files].sort() }, null, 2)}\n`;
}

function trimUnescapedTrailingSpaces(value) {
  let end = value.length;
  while (end > 0 && value[end - 1] === " ") {
    let backslashes = 0;
    for (let index = end - 2; index >= 0 && value[index] === "\\"; index -= 1) backslashes += 1;
    if (backslashes % 2 === 1) break;
    end -= 1;
  }
  return value.slice(0, end);
}

function escapeRegex(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function globRegexSource(glob) {
  let source = "";
  for (let index = 0; index < glob.length; index += 1) {
    const character = glob[index];
    if (character === "\\" && index + 1 < glob.length) {
      source += escapeRegex(glob[index + 1]);
      index += 1;
    } else if (character === "*") {
      if (glob[index + 1] === "*") {
        while (glob[index + 1] === "*") index += 1;
        if (glob[index + 1] === "/") {
          source += "(?:.*/)?";
          index += 1;
        } else source += ".*";
      } else source += "[^/]*";
    } else if (character === "?") source += "[^/]";
    else if (character === "[") {
      const close = glob.indexOf("]", index + 1);
      if (close === -1) source += "\\[";
      else {
        let content = glob.slice(index + 1, close);
        if (content.startsWith("!")) content = `^${content.slice(1)}`;
        else if (content.startsWith("^")) content = `\\${content}`;
        source += `[${content.replace(/\\/g, "\\\\")}]`;
        index = close;
      }
    } else source += escapeRegex(character);
  }
  return source;
}

function readIgnorePatterns(root) {
  const ignoreFile = path.join(root, IGNORE_FILE);
  if (!exists(ignoreFile)) return [];
  const stat = fs.lstatSync(ignoreFile);
  if (!stat.isFile() || stat.isSymbolicLink()) throw new OverlayError(`${IGNORE_FILE} must be a regular file: ${ignoreFile}`);
  const patterns = [];
  for (const rawLine of fs.readFileSync(ignoreFile, "utf8").split(/\r?\n/)) {
    let pattern = trimUnescapedTrailingSpaces(rawLine);
    if (!pattern || pattern.startsWith("#")) continue;
    let negated = false;
    if (pattern.startsWith("!")) {
      negated = true;
      pattern = pattern.slice(1);
    }
    const directoryOnly = pattern.endsWith("/");
    if (directoryOnly) pattern = pattern.slice(0, -1);
    const anchored = pattern.startsWith("/");
    if (anchored) pattern = pattern.slice(1);
    if (!pattern) continue;
    const basenameOnly = !anchored && !pattern.includes("/");
    const source = globRegexSource(pattern);
    patterns.push({
      negated,
      directoryOnly,
      regex: new RegExp(basenameOnly ? `(?:^|/)${source}$` : `^${source}$`),
    });
  }
  return patterns;
}

function ignoredByPatterns(relative, isDirectory, patterns) {
  let ignored = false;
  for (const pattern of patterns) {
    if ((!pattern.directoryOnly || isDirectory) && pattern.regex.test(relative)) ignored = !pattern.negated;
  }
  return ignored;
}

function scanOverlay(root) {
  if (!exists(root)) throw new OverlayError(`Overlay directory is missing: ${root}`);
  const ignorePatterns = readIgnorePatterns(root);
  const files = [];
  function visit(directory, prefix = "") {
    const entries = fs.readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
    for (const entry of entries) {
      const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
      validateRelativePath(relative);
      const absolute = path.join(directory, entry.name);
      if (relative === IGNORE_FILE || ignoredByPatterns(relative, entry.isDirectory(), ignorePatterns)) continue;
      if (entry.isDirectory() && prefix === SKILLS_DIR) files.push(relative);
      else if (entry.isDirectory()) visit(absolute, relative);
      else if (entry.isFile()) files.push(relative);
      else if (entry.isSymbolicLink()) {
        let target;
        try { target = fs.statSync(absolute); } catch { throw new OverlayError(`Broken overlay source symlink: ${relative}`); }
        if (target.isDirectory()) throw new OverlayError(`Overlay directory symlinks are not supported: ${relative}`);
        files.push(relative);
      }
      else throw new OverlayError(`Unsupported overlay entry: ${relative}`);
    }
  }
  visit(root);
  return files.sort();
}

function trackedAtOrBelow(repoRoot, relative) {
  return runGit(repoRoot, ["ls-files", "--", `:(literal)${relative}`]).stdout.trim().length > 0;
}

function managedBlock(files) {
  const escapePattern = (value) => value.replace(/[?*\[\]]/g, "\\$&");
  const entries = ["/.agent-workspaces/", "/AGENTS.override.md", ...files.map((file) => `/${escapePattern(file)}`)];
  return [BLOCK_START, ...entries, BLOCK_END].join("\n");
}

function replaceManagedBlock(content, files) {
  const newline = content.includes("\r\n") ? "\r\n" : "\n";
  const lines = content.length === 0 ? [] : content.replace(/\r\n/g, "\n").split("\n");
  if (lines.at(-1) === "") lines.pop();
  const starts = lines.flatMap((line, index) => line === BLOCK_START ? [index] : []);
  const ends = lines.flatMap((line, index) => line === BLOCK_END ? [index] : []);
  if (starts.length > 1 || ends.length > 1 || starts.length !== ends.length || (starts.length === 1 && starts[0] > ends[0])) {
    throw new OverlayError("Git exclude file contains malformed awso markers.");
  }
  const block = managedBlock(files).split("\n");
  if (starts.length === 0) {
    if (lines.length > 0 && lines.at(-1) !== "") lines.push("");
    lines.push(...block);
  } else {
    lines.splice(starts[0], ends[0] - starts[0] + 1, ...block);
  }
  return `${lines.join(newline)}${newline}`;
}

function expectedExclude(paths, files) {
  const current = exists(paths.exclude) ? fs.readFileSync(paths.exclude, "utf8") : "";
  return replaceManagedBlock(current, files);
}

function assertWorkspace(paths) {
  for (const [label, target] of [["workspace", paths.root], ["overlay", paths.overlay], ["sources", paths.sources]]) {
    if (!exists(target)) throw new OverlayError(`Workspace ${label} directory is missing: ${target}`);
    const stat = fs.lstatSync(target);
    if (!stat.isDirectory() || stat.isSymbolicLink()) throw new OverlayError(`Workspace ${label} must be a real directory: ${target}`);
  }
  if (!exists(paths.extend) || !fs.lstatSync(paths.extend).isFile()) throw new OverlayError(`Personal extension file must be a regular file: ${paths.extend}`);
}

function ensureRealDirectory(target, label, created) {
  if (!exists(target)) {
    fs.mkdirSync(target);
    created.push(label);
    return;
  }
  const stat = fs.lstatSync(target);
  if (!stat.isDirectory() || stat.isSymbolicLink()) throw new OverlayError(`Workspace directory must not be a symlink: ${target}`);
}

function setup(cwd) {
  const repo = discoverRepository(cwd);
  const paths = workspacePaths(repo);
  const created = [];
  ensureRealDirectory(paths.root, `${WORKSPACE_DIR}/`, created);
  ensureRealDirectory(paths.sources, `${WORKSPACE_DIR}/${SOURCES_DIR}/`, created);
  ensureRealDirectory(paths.overlay, `${WORKSPACE_DIR}/${OVERLAY_DIR}/`, created);
  const ignoreFile = path.join(paths.overlay, IGNORE_FILE);
  if (!exists(ignoreFile)) {
    atomicWrite(ignoreFile, "# Files matching these patterns stay in the overlay and are not linked.\n");
    created.push(`${WORKSPACE_DIR}/${OVERLAY_DIR}/${IGNORE_FILE}`);
  }
  if (!exists(paths.extend)) {
    atomicWrite(paths.extend, "# Personal agent instructions\n\n");
    created.push(`${WORKSPACE_DIR}/${SOURCES_DIR}/${EXTEND_FILE}`);
  }
  assertWorkspace(paths);
  if (!exists(paths.manifest)) {
    atomicWrite(paths.manifest, manifestText([]));
    created.push(`${WORKSPACE_DIR}/${MANIFEST_FILE}`);
  } else {
    readManifest(paths.manifest);
  }
  const files = readManifest(paths.manifest).files;
  const exclude = expectedExclude(paths, files);
  const oldExclude = exists(paths.exclude) ? fs.readFileSync(paths.exclude, "utf8") : "";
  if (exclude !== oldExclude) atomicWrite(paths.exclude, exclude);
  console.log("Workspace overlay initialized.\n");
  console.log(`Main worktree:\n  ${repo.mainRoot}\n\nWorkspace:\n  ${paths.root}`);
  if (created.length) console.log(`\nCreated:\n${created.map((item) => `  ${item}`).join("\n")}`);
  console.log(exclude === oldExclude ? "\nGit exclusions already configured." : "\nUpdated Git exclusions.");
  return 0;
}

function update(cwd) {
  const repo = discoverRepository(cwd);
  const paths = workspacePaths(repo);
  assertWorkspace(paths);
  const previous = readManifest(paths.manifest).files;
  const files = scanOverlay(paths.overlay);
  const conflicts = files.filter((file) => trackedAtOrBelow(repo.currentRoot, file));
  if (conflicts.length) throw new OverlayError(`Overlay paths conflict with tracked repository files:\n${conflicts.map((file) => `  ${file}`).join("\n")}`);
  const before = new Set(previous);
  const after = new Set(files);
  const added = files.filter((file) => !before.has(file));
  const removed = previous.filter((file) => !after.has(file));
  const nextManifest = manifestText(files);
  const nextExclude = expectedExclude(paths, files);
  const manifestChanged = fs.readFileSync(paths.manifest, "utf8") !== nextManifest;
  const excludeChanged = !exists(paths.exclude) || fs.readFileSync(paths.exclude, "utf8") !== nextExclude;
  if (excludeChanged) atomicWrite(paths.exclude, nextExclude);
  if (manifestChanged) atomicWrite(paths.manifest, nextManifest);
  if (!manifestChanged && !excludeChanged) console.log(`Workspace overlay already up to date.\n\n${files.length} overlay entries\n0 added\n0 removed\n0 conflicts`);
  else {
    console.log("Workspace overlay updated.");
    if (added.length) console.log(`\nAdded:\n${added.map((file) => `  ${file}`).join("\n")}`);
    if (removed.length) console.log(`\nRemoved:\n${removed.map((file) => `  ${file}`).join("\n")}`);
    console.log(`\nCurrent overlay:\n  ${files.length} entries\n\nGit exclusions updated.`);
  }
  return 0;
}

function resolveLink(link) {
  const target = fs.readlinkSync(link);
  return path.resolve(path.dirname(link), target);
}

function overlayOwnedLink(link, relative) {
  const suffix = path.join(WORKSPACE_DIR, OVERLAY_DIR, ...relative.split("/"));
  return resolveLink(link).endsWith(`${path.sep}${suffix}`);
}

function isSkillDirectory(relative) {
  const name = relative.startsWith(`${SKILLS_DIR}/`) ? relative.slice(SKILLS_DIR.length + 1) : "";
  return name.length > 0 && !name.includes("/");
}

function replaceableLegacySkillDirectory(directory, sourceDirectory) {
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const child = path.join(directory, entry.name);
    const childSource = path.join(sourceDirectory, entry.name);
    if (entry.isDirectory()) {
      if (!replaceableLegacySkillDirectory(child, childSource)) return false;
    } else if (!entry.isSymbolicLink() || resolveLink(child) !== childSource) return false;
  }
  return true;
}

function inspectDestination(destination, source, relative) {
  if (!exists(destination)) return { kind: "missing" };
  const stat = fs.lstatSync(destination);
  if (stat.isDirectory() && isSkillDirectory(relative) && replaceableLegacySkillDirectory(destination, source)) {
    return { kind: "repairable-directory" };
  }
  if (!stat.isSymbolicLink()) return { kind: "collision", detail: "a non-symlink entry exists" };
  const actual = resolveLink(destination);
  if (actual === source) return { kind: "linked" };
  if (overlayOwnedLink(destination, relative)) return { kind: "repairable", actual };
  return { kind: "wrong", actual };
}

function assertSafeParents(root, relative, create) {
  let current = root;
  for (const part of relative.split("/").slice(0, -1)) {
    current = path.join(current, part);
    if (!exists(current)) {
      if (create) fs.mkdirSync(current);
      else return { kind: "missing-parent", path: current };
    } else {
      const stat = fs.lstatSync(current);
      if (!stat.isDirectory() || stat.isSymbolicLink()) return { kind: "unsafe-parent", path: current };
    }
  }
  return null;
}

function renderOverride(repo, paths) {
  const agents = path.join(repo.currentRoot, "AGENTS.md");
  const chunks = [
    "<!--\nGENERATED BY awso.\nDo not edit this file directly.\n\nSources:\n- AGENTS.md\n- .agent-workspaces/sources/AGENTS.extend.md\n-->\n",
  ];
  const withFinalNewline = (content) => !content || content.endsWith("\n") ? content : `${content}\n`;
  if (exists(agents)) chunks.push(withFinalNewline(fs.readFileSync(agents, "utf8")));
  const extension = withFinalNewline(fs.readFileSync(paths.extend, "utf8"));
  if (chunks.length > 1 && extension.length) chunks.push("\n");
  if (extension.length) chunks.push(extension);
  return chunks.join("");
}

function writeOverride(file, content) {
  if (exists(file)) {
    const stat = fs.lstatSync(file);
    if (stat.isDirectory()) throw new OverlayError(`AGENTS.override.md must not be a directory: ${file}`);
    if (stat.isSymbolicLink()) fs.unlinkSync(file);
    else if (!stat.isFile()) throw new OverlayError(`AGENTS.override.md must be a regular file or symlink: ${file}`);
  }
  atomicWrite(file, content);
}

function restore(cwd) {
  const repo = discoverRepository(cwd);
  const paths = workspacePaths(repo);
  assertWorkspace(paths);
  const manifest = readManifest(paths.manifest);
  const counts = { created: 0, unchanged: 0, repaired: 0, conflicts: 0 };
  const details = [];
  for (const relative of manifest.files) {
    const source = path.join(paths.overlay, ...relative.split("/"));
    const destination = path.join(repo.currentRoot, ...relative.split("/"));
    if (trackedAtOrBelow(repo.currentRoot, relative)) { counts.conflicts += 1; details.push(`TRACKED  ${relative}`); continue; }
    if (!exists(source)) { counts.conflicts += 1; details.push(`NO SOURCE  ${relative}`); continue; }
    const parentProblem = assertSafeParents(repo.currentRoot, relative, true);
    if (parentProblem) { counts.conflicts += 1; details.push(`UNSAFE PARENT  ${relative}`); continue; }
    const state = inspectDestination(destination, source, relative);
    if (state.kind === "missing") { fs.symlinkSync(source, destination); counts.created += 1; }
    else if (state.kind === "linked") counts.unchanged += 1;
    else if (state.kind === "repairable") { fs.unlinkSync(destination); fs.symlinkSync(source, destination); counts.repaired += 1; }
    else if (state.kind === "repairable-directory") { fs.rmSync(destination, { recursive: true }); fs.symlinkSync(source, destination); counts.repaired += 1; }
    else { counts.conflicts += 1; details.push(`CONFLICT  ${relative}${state.actual ? ` -> ${state.actual}` : ""}`); }
  }
  writeOverride(paths.override, renderOverride(repo, paths));
  console.log(`Workspace overlay restored.\n\nStatic overlay:\n  ${counts.unchanged} unchanged\n  ${counts.created} created\n  ${counts.repaired} repaired\n  ${counts.conflicts} conflicts`);
  if (details.length) console.log(`\n${details.join("\n")}`);
  console.log("\nAGENTS.override.md:\n  regenerated");
  if (counts.conflicts) return 3;
  console.log("\nWorktree is ready.");
  return 0;
}

function status(cwd) {
  let repo;
  try { repo = discoverRepository(cwd); } catch (error) { console.error(error.message); return 3; }
  const paths = workspacePaths(repo);
  const invalid = [];
  const updateNeeded = [];
  const restoreNeeded = [];
  let exclusions = "UNKNOWN";
  let manifest;
  try { assertWorkspace(paths); manifest = readManifest(paths.manifest); } catch (error) { invalid.push(error.message); }
  let actual = [];
  if (manifest) {
    try {
      actual = scanOverlay(paths.overlay);
      if (JSON.stringify(actual) !== JSON.stringify([...manifest.files].sort())) updateNeeded.push("manifest does not match overlay contents");
      const currentExclude = exists(paths.exclude) ? fs.readFileSync(paths.exclude, "utf8") : "";
      if (currentExclude !== expectedExclude(paths, [...manifest.files].sort())) {
        exclusions = "OUT OF DATE";
        updateNeeded.push("Git exclusions are out of date");
      } else exclusions = "OK";
    } catch (error) { invalid.push(error.message); }
  }
  const rows = [];
  if (manifest) for (const relative of manifest.files) {
    const source = path.join(paths.overlay, ...relative.split("/"));
    const destination = path.join(repo.currentRoot, ...relative.split("/"));
    let state;
    if (trackedAtOrBelow(repo.currentRoot, relative)) state = "TRACKED";
    else if (!exists(source)) state = "NO SOURCE";
    else if (assertSafeParents(repo.currentRoot, relative, false)?.kind === "unsafe-parent") state = "UNSAFE";
    else state = inspectDestination(destination, source, relative).kind.toUpperCase();
    rows.push(`${state.padEnd(10)} ${relative}`);
    if (state !== "LINKED") (state === "TRACKED" || state === "UNSAFE" || state === "COLLISION" || state === "WRONG" ? invalid : restoreNeeded).push(relative);
  }
  let override = "missing";
  if (manifest && exists(paths.extend)) {
    if (exists(paths.override)) {
      const stat = fs.lstatSync(paths.override);
      if (stat.isFile() && fs.readFileSync(paths.override, "utf8") === renderOverride(repo, paths)) override = "OK";
      else if (stat.isFile() || stat.isSymbolicLink()) { override = "stale"; restoreNeeded.push(OVERRIDE_FILE); }
      else { override = "conflict"; invalid.push("AGENTS.override.md is not a regular file or symlink"); }
    } else restoreNeeded.push(OVERRIDE_FILE);
  }
  const exitCode = invalid.length ? 3 : updateNeeded.length ? 2 : restoreNeeded.length ? 1 : 0;
  const label = exitCode === 0 ? "healthy" : exitCode === 1 ? "restore required" : exitCode === 2 ? "update required" : "conflict or invalid configuration";
  console.log(`Workspace overlay status\n\nRepository:\n  ${repo.mainRoot}\n\nCurrent worktree:\n  ${repo.currentRoot}\n\nMain worktree:\n  ${repo.mainRoot}`);
  console.log(`\nWorkspace:\n  ${invalid.length ? "INVALID" : "OK"}`);
  console.log(`\nManifest:\n  ${updateNeeded.length ? "OUT OF DATE" : manifest ? "OK" : "INVALID"}${manifest ? `\n  ${manifest.files.length} entries` : ""}`);
  console.log(`\nGit exclusions:\n  ${exclusions}`);
  console.log(`\nStatic overlay:${rows.length ? `\n${rows.map((row) => `  ${row}`).join("\n")}` : "\n  0 files"}`);
  console.log(`\nAGENTS.override.md:\n  ${override}\n\nStatus:\n  ${label}`);
  for (const message of [...new Set([...invalid, ...updateNeeded])]) console.log(`\n  ${message}`);
  if (exitCode === 1) console.log("\nRun:\n  awso restore");
  if (exitCode === 2) console.log("\nRun:\n  awso update");
  return exitCode;
}

function help() {
  console.log(`Usage: awso <command>

Commands:
  setup    Initialize awso for a Git repository
  update   Synchronize the overlay manifest and Git exclusions
  restore  Hydrate the current worktree
  status   Check the current awso installation
  help     Show this help message`);
  return 0;
}

export function main(argv = process.argv.slice(2), cwd = process.cwd()) {
  if (argv.length !== 1 || !["setup", "update", "restore", "status", "help"].includes(argv[0])) {
    console.error("Usage: awso <setup|update|restore|status|help>");
    return 3;
  }
  try {
    return { setup, update, restore, status, help }[argv[0]](cwd);
  } catch (error) {
    console.error(`ERROR: ${error.message}`);
    return error.exitCode ?? 3;
  }
}

const invokedDirectly = process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href;
if (invokedDirectly) process.exitCode = main();
